from typing import List
import models

# KumoMTA standard paths on Linux
KUMOMTA_DATA_DIR = "/var/lib/kumomta/data"
KUMOMTA_DKIM_DIR = f"{KUMOMTA_DATA_DIR}/dkim"


def _ip_name(ip: models.IPAddress) -> str:
    """Safe Lua identifier for an IP: use label or replace dots with underscores."""
    return (ip.label or ip.ip).replace(".", "_").replace("-", "_").replace(" ", "_")


def generate_init_lua(ips: List[models.IPAddress], dkim_keys: List[models.DKIMKey], relay_hosts: str = "127.0.0.1,::1") -> str:
    pools: dict[str, List[models.IPAddress]] = {}
    for ip in ips:
        pools.setdefault(ip.pool_name, []).append(ip)

    lines = [
        "-- Auto-generated by KumoMTA Panel",
        "-- DO NOT EDIT MANUALLY — regenerate from the dashboard",
        "",
        'local kumo = require "kumo"',
        "",
        "-- -------------------------------------------------------",
        "-- Startup: spool + listeners",
        "-- -------------------------------------------------------",
        "kumo.on('init', function()",
        "  -- Spool storage (required by KumoMTA)",
        "  kumo.define_spool {",
        "    name = 'data',",
        "    path = '/var/spool/kumomta/data',",
        "  }",
        "  kumo.define_spool {",
        "    name = 'meta',",
        "    path = '/var/spool/kumomta/meta',",
        "  }",
        "",
        "  -- Accept inbound SMTP relay",
        "  kumo.start_esmtp_listener {",
        "    listen = '0.0.0.0:25',",
        "    relay_hosts = { " + ", ".join(f"'{h.strip()}'" for h in relay_hosts.split(",") if h.strip()) + " },",
        "  }",
        "",
        "  -- HTTP management API (localhost only — accessed by the panel)",
        "  kumo.start_http_listener {",
        "    listen = '127.0.0.1:8001',",
        "  }",
        "",
        "  -- Delivery logs (zstd-compressed JSONL in /var/log/kumomta/)",
        "  kumo.configure_local_logs {",
        "    log_dir = '/var/log/kumomta',",
        "    max_segment_duration = '1 minute',",
        "  }",
        "end)",
        "",
    ]

    # -----------------------------------------------------------
    # Egress sources (one per IP)
    # -----------------------------------------------------------
    lines += [
        "-- -------------------------------------------------------",
        "-- Egress sources: one entry per sending IP",
        "-- -------------------------------------------------------",
        "kumo.on('get_egress_source', function(source_name)",
    ]
    if ips:
        for ip in ips:
            name = _ip_name(ip)
            ehlo_line = f"      ehlo_domain = '{ip.hostname}'," if ip.hostname else ""
            block = [
                f"  if source_name == '{name}' then",
                "    return kumo.make_egress_source {",
                f"      name = '{name}',",
                f"      source_address = '{ip.ip}',",
            ]
            if ehlo_line:
                block.append(ehlo_line)
            block += ["    }", "  end"]
            lines += block
    lines += [
        "  -- Fallback: let the OS choose the source address",
        "  return kumo.make_egress_source { name = source_name }",
        "end)",
        "",
    ]

    # -----------------------------------------------------------
    # Egress pools (group IPs together)
    # -----------------------------------------------------------
    lines += [
        "-- -------------------------------------------------------",
        "-- Egress pools: group IPs for load balancing",
        "-- -------------------------------------------------------",
        "kumo.on('get_egress_pool', function(pool_name)",
    ]
    if pools:
        for pool_name, pool_ips in pools.items():
            entries = ", ".join(
                f"{{ name = '{_ip_name(ip)}', weight = 1 }}" for ip in pool_ips
            )
            lines += [
                f"  if pool_name == '{pool_name}' then",
                "    return kumo.make_egress_pool {",
                f"      name = '{pool_name}',",
                f"      entries = {{ {entries} }},",
                "    }",
                "  end",
            ]
    lines += [
        "  -- Default pool: single source matching the pool name",
        "  return kumo.make_egress_pool {",
        "    name = pool_name,",
        "    entries = { { name = pool_name } },",
        "  }",
        "end)",
        "",
    ]

    # -----------------------------------------------------------
    # Queue config: assign egress pool
    # -----------------------------------------------------------
    default_pool = list(pools.keys())[0] if pools else "default"
    lines += [
        "-- -------------------------------------------------------",
        "-- Queue config: assign egress pool",
        "-- -------------------------------------------------------",
        "kumo.on('get_queue_config', function(domain, tenant, campaign, routing_domain)",
        f"  return kumo.make_queue_config {{",
        f"    egress_pool = '{default_pool}',",
        "  }",
        "end)",
        "",
    ]

    # -----------------------------------------------------------
    # DKIM signing
    # -----------------------------------------------------------
    if dkim_keys:
        lines += [
            "-- -------------------------------------------------------",
            "-- DKIM signing: sign outbound messages per sender domain",
            "-- -------------------------------------------------------",
            "kumo.on('smtp_server_message_received', function(msg)",
            "  local from_domain = msg:sender().domain",
        ]
        for key in dkim_keys:
            key_path = f"{KUMOMTA_DKIM_DIR}/{key.domain}/{key.selector}.key"
            lines += [
                f"  if from_domain == '{key.domain}' then",
                "    local ok, err = pcall(function()",
                "      local signer = kumo.dkim.rsa_sha256_signer {",
                f"        domain = '{key.domain}',",
                f"        selector = '{key.selector}',",
                "        headers = { 'From', 'To', 'Subject', 'Date', 'Message-Id' },",
                f"        key = '{key_path}',",
                "      }",
                "      msg:dkim_sign(signer)",
                "    end)",
                "    if not ok then",
                f"      kumo.log('WARN', 'DKIM signing failed for {key.domain}: ' .. tostring(err))",
                "    end",
                "  end",
            ]
        lines += ["end)", ""]
    else:
        lines += [
            "kumo.on('smtp_server_message_received', function(msg)",
            "  -- No DKIM keys configured yet",
            "end)",
            "",
        ]

    # kumo.make_egress_path_config does not exist in KumoMTA 2026.x
    # omit the get_egress_path_config handler — KumoMTA uses built-in defaults

    return "\n".join(lines)


def generate_shaping_toml(domain_rules: List[models.DomainRule]) -> str:
    """
    Generates shaping.toml used by KumoMTA's policy-extras.shaping module.
    KumoMTA reads this via: require 'policy-extras.shaping'
    """
    lines = [
        "# Auto-generated by KumoMTA Panel",
        "# DO NOT EDIT MANUALLY — regenerate from the dashboard",
        "# Place this file at: /opt/kumomta/etc/policy/shaping.toml",
        "",
    ]

    for rule in domain_rules:
        lines += [
            f'["{rule.domain}"]',
            f"connection_limit = {rule.max_connections}",
            f'max_message_rate = "{rule.max_per_minute}/min"',
            "",
        ]

    return "\n".join(lines)


def get_dkim_key_path(domain: str, selector: str) -> str:
    """Returns the expected filesystem path for a DKIM private key."""
    return f"{KUMOMTA_DKIM_DIR}/{domain}/{selector}.key"
